# Generated by Django 5.0.6 on 2024-06-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_roomno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomNo',
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(default='PUNE', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomType',
            field=models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK')], max_length=200),
        ),
    ]
