# Generated by Django 5.0.6 on 2024-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
