# Generated by Django 5.0.6 on 2024-06-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
