# Generated by Django 5.0.6 on 2024-06-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_alter_room_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
