# Generated by Django 5.0.6 on 2024-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_remove_room_duration_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(blank=True, default='C:\\Users\\Vijay\\django_pro\\hotels\\media\\roomImages\\istockphoto-1125725514-170667a.webp', null=True, upload_to='roomImages/'),
        ),
    ]
